# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-18 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'scrapper_keyword',
            },
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link', models.URLField(max_length=1023)),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=255)),
                ('scanned_at', models.DateTimeField(default=None, null=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrapper.Keyword')),
            ],
            options={
                'db_table': 'scrapper_profiles',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'scrapper_segment',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1023)),
                ('password', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('strategy', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'scrapper_site',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('in_process', models.BooleanField(default=0)),
                ('scanned_at', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrapper.Keyword')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrapper.Site')),
            ],
            options={
                'db_table': 'scrapper_task',
            },
        ),
        migrations.AddField(
            model_name='profiles',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrapper.Segment'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrapper.Task'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrapper.Segment'),
        ),
    ]
