# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-18 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='outer_id',
            field=models.CharField(default=None, max_length=1023, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='scrapper.Site'),
            preserve_default=False,
        ),
    ]
