# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-19 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_auto_20180418_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='task',
            name='limit',
            field=models.IntegerField(default=10),
        ),
    ]
