# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-19 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0009_auto_20180419_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiondict',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
