# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-19 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0010_auto_20180419_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiondict',
            name='town_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regiondict',
            name='town_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
