# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0013_auto_20180419_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='search_params',
            field=models.TextField(default=None, null=True),
        ),
    ]
