# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0014_auto_20180419_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='keyword',
            field=models.CharField(max_length=255),
        ),
    ]
