# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0016_auto_20180419_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='total_found',
            field=models.IntegerField(default=0),
        ),
    ]
