# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-20 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0017_task_total_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='segment',
            field=models.CharField(max_length=255),
        ),
    ]
