# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-23 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0019_task_segment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='in_process',
            new_name='status',
        ),
    ]
