# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-23 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0020_auto_20180423_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
