# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-24 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0021_auto_20180423_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='strategy',
        ),
    ]
