# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0022_remove_site_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_id',
            field=models.CharField(default=None, max_length=1023, null=True),
        ),
    ]
