# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0023_profile_resume_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
