# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0027_auto_20180425_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_provider',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
