# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-15 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0028_profile_email_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='duplicate',
            field=models.SmallIntegerField(default=0),
        ),
    ]
